# Site settings
title: Achu Wilson
email: achuwilson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love Robots
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://achuwilson.github.io/" # the base hostname & protocol for your site
twitter_username: achuwilson
github_username:  achuwilson

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
job.title: "Chief Technology Officer"
excerpt_separator: "<!--more-->"

google_analytics: UA-44991178-2
# SEO stuff
#google_author: "https://plus.google.com/u/0/110288225974212014913"
#google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
#bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

gems:
  - jekyll-sitemap
